export const REQUEST_HOTELS = 'REQUEST_HOTELS';
export const REQUEST_HOTELS_SUCCESS = 'REQUEST_HOTELS_SUCCESS';
export const REQUEST_HOTELS_FAILED = 'REQUEST_HOTELS_FAILED';
export const FETCH_HOTELS = 'FETCH_HOTELS';
